-- 002_stage1_events.sql

-- Adapt existing table to canonical OperationalEvent schema
ALTER TABLE events RENAME COLUMN external_id TO event_id;
ALTER TABLE events RENAME COLUMN type TO event_type;

ALTER TABLE events ADD COLUMN source TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE events ADD COLUMN entity_type TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE events ADD COLUMN entity_id TEXT NOT NULL DEFAULT 'unknown';
ALTER TABLE events ADD COLUMN correlation_id TEXT;
ALTER TABLE events ADD COLUMN schema_version INTEGER NOT NULL DEFAULT 1;

-- Drop the old single-column unique constraint.
-- Note: 'events_external_id_key' is the default name generated by PostgreSQL for `external_id TEXT UNIQUE`.
ALTER TABLE events DROP CONSTRAINT IF EXISTS events_external_id_key;

-- Add the new composite unique constraint enforcing Event Identity Scope
ALTER TABLE events ADD CONSTRAINT events_source_event_id_key UNIQUE (source, event_id);

-- Update the types index
DROP INDEX IF EXISTS idx_events_type;
CREATE INDEX IF NOT EXISTS idx_events_event_type ON events (event_type);
